name: bytepower_room
room_server:
    url: "localhost:8090"
    pprof_url: "localhost:9090"
    
redis_cluster:
    addrs: 
      - "127.0.0.1:30001"
      - "127.0.0.1:30002"
      - "127.0.0.1:30003"
    pool_size: 600
    min_idle_conns: 300
    dial_timeout_ms: 1000
    pool_timeout_ms: 1000
    idle_timeout_ms: 12000
    read_timeout_ms: 100
    write_timeout_ms: 100

log:
    server:
      console:
        level: debug
    task:
      console:
        level: debug


metric:
  prefix: "bytepower_room.service"
  host: "127.0.0.1:8125"

# vector, collect access information
event_service:
  tcp:
    dsn: "127.0.0.1:7006"
    timeout: 3
    write_timeout: 0
  event_buffer:
    buffer_limit: 1024
    worker_count: 3
    worker_process_bulk_size: 50
    worker_process_interval: 1m
    worker_drain_duration: 5s

    
# 用于同步数据的后端数据库
db_cluster:
    sharding_count: 5
    shardings:
      - url: postgres://root:root123@127.0.0.1:5433/room_service?sslmode=disable
        conn_max_lifetime_sec: 3600
        max_open_conns: 100
        min_idle_conns: 10
        max_retries: 5
        start_index: 0
        end_index: 1

      - url: postgres://root:root123@127.0.0.1:5433/room_service2?sslmode=disable
        conn_max_lifetime_sec: 3600
        max_open_conns: 100
        min_idle_conns: 10
        max_retries: 5
        start_index: 2
        end_index: 4
sync:
  metric:
    prefix: "bytepower_room.task"
    host: "127.0.0.1:8125"
  written_record_db_cluster:
      sharding_count: 10
      shardings:
        - url: postgres://root:root123@127.0.0.1:5433/room_service?sslmode=disable
          conn_max_lifetime_sec: 3600
          max_open_conns: 100
          min_idle_conns: 10
          max_retries: 5
          start_index: 0
          end_index: 5

        - url: postgres://root:root123@127.0.0.1:5433/room_service2?sslmode=disable
          conn_max_lifetime_sec: 3600
          max_open_conns: 100
          min_idle_conns: 10
          max_retries: 5
          start_index: 6
          end_index: 9

  accessed_record_db_cluster:
      sharding_count: 5
      shardings:
        - url: postgres://root:root123@127.0.0.1:5433/room_service?sslmode=disable
          conn_max_lifetime_sec: 3600
          max_open_conns: 100
          min_idle_conns: 10
          max_retries: 5
          start_index: 0
          end_index: 1

        - url: postgres://root:root123@127.0.0.1:5433/room_service2?sslmode=disable
          conn_max_lifetime_sec: 3600
          max_open_conns: 100
          min_idle_conns: 10
          max_retries: 5
          start_index: 2
          end_index: 4
  sqs:
    queue: "sqs_queue_name"
    max_received_messages: 5
    visibility_timeout_seconds: 300
    wait_time_seconds: 5
    aws_access_key_id: {aws_access_key_id}
    aws_secret_access_key: {aws_secret_access_key}
    region: {aws_region}
  s3:
    aws_access_key_id: {aws_access_key_id}
    aws_secret_access_key: {aws_secret_access_key}
    region: {aws_region}
  coordinator:
    name: "room_sync"
    addrs:
      - "127.0.0.1:30001"
      - "127.0.0.1:30002"
      - "127.0.0.1:30003"
  sync_record_task:
    interval_minutes: 5
    off: false
  sync_key_task:
    interval_minutes: 5
    off: false
  clean_key_task:
    interval_minutes: 10
    # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    inactive_duration: 2h
    off: false
    
